services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${DOMAIN_WIREGUARD}
      # Optional:
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # -> https://www.reddit.com/r/docker/comments/14isrlg/docker_swarm_running_a_wireguard_server/
      - WG_POST_UP=iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -j MASQUERADE; iptables -A FORWARD -o %i -j ACCEPT
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - WG_POST_DOWN=iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -j MASQUERADE; iptables -D FORWARD -o %i -j ACCEPT
      # - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        # TODO: redirect http to https
        # actual server
        - "traefik.http.routers.wireguard-ui-https.rule=Host(`${DOMAIN_WIREGUARD}`)"
        - "traefik.http.routers.wireguard-ui-https.entrypoints=https"
        - "traefik.http.routers.wireguard-ui-https.tls=true"
        # explicitly use le as certresolver
        - "traefik.http.routers.wireguard-ui-https.tls.certresolver=letsencrypt"
        # "secure" ui using admin basic auth
        - "traefik.http.routers.wireguard-ui-https.middlewares=admin-basic-auth@file"
        - "traefik.http.routers.wireguard-ui-https.service=wireguardUiService"
        - "traefik.http.services.wireguardUiService.loadbalancer.server.port=51821"
    volumes:
      - etc-wireguard:/etc/wireguard
    networks:
      - traefik-public
    ports:
      - "51820:51820/udp"
      # uncomment this only, if you want to access the web ui via http for TESTING purposes
#      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  etc-wireguard:

networks:
  traefik-public:
    external: true
