configs:
  services-yml:
    file: ./services.yml
  traefik-yml:
    file: ./traefik.yml


services:
  reverse-proxy:
    image: traefik:v2.4
    configs:
      - source: services-yml
        target: /etc/traefik/services.yml
      - source: traefik-yml
        target: /etc/traefik/traefik.yml
    deploy:
        placement:
            constraints:
            - node.role == manager
    ports:
      # The HTTP port
      - "80:80"
      # HTTPS also
      - "443:443"
      # publish The Web UI (enabled by --api.insecure=true)
      # on a public port, uncomment to be able to reach it without DNS
      # but only for testing purposes!
#      - "8080:8080"
    volumes:
      # Add Docker socket as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # acme.json for le challenges
      - acme-data:/letsencrypt
    networks:
      - traefik-public

# comment the following if you do not want to use the example whoami service
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        # explicit http entrypoint
        - "traefik.http.routers.whoami-http.rule=Host(`${DOMAIN_WHOAMI}`)"
        - "traefik.http.routers.whoami-http.entrypoints=http"
        - "traefik.http.routers.whoami-http.service=whoamiService"
        - "traefik.http.services.whoamiService.loadbalancer.server.port=80"
        # https entrypoint
        - "traefik.http.routers.whoami-https.rule=Host(`${DOMAIN_WHOAMI}`)"
        - "traefik.http.routers.whoami-https.entrypoints=https"
        - "traefik.http.routers.whoami-https.tls=true"
        # explicitly use le as certresolver
        - "traefik.http.routers.whoami-https.tls.certresolver=letsencrypt"
        - "traefik.http.routers.whoami-https.service=whoamiHttpsService"
        - "traefik.http.services.whoamiHttpsService.loadbalancer.server.port=80"
    networks:
      - traefik-public

volumes:
  acme-data:

networks:
  # N.B. this must be created once on a manager node (e.g. docker network create --driver=overlay traefik-public)
  traefik-public:
    external: true
