name: Build Images
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
    - uses: actions/checkout@v4
    # For pull requests it's not necessary to checkout the code but for the main branch it is
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          docs:
            - README.md
            - docs/**
            - requirements-docs.txt
            - requirements-docs-insiders.txt
            - pyproject.toml
            - mkdocs.yml
            - mkdocs.insiders.yml
            - mkdocs.maybe-insiders.yml
            - mkdocs.no-insiders.yml
            - .github/workflows/build-docs.yml
            - .github/workflows/deploy-docs.yml

  build-docs:
    needs:
      - changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: |
          VERSION=$(git describe --tags --abbrev=0) docker compose build

      - name: Push Docker images
        run: |
          VERSION=$(git describe --tags --abbrev=0) docker compose push
        
      
      
