name: Deploy Stack
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      stage:
        required: true
        type: string
      deployUrl:
        required: true
        type: string
      stack:
        required: true
        type: string
    secrets:
      DOCKER_SWARM_MANAGER_SSH_KEY:
        required: true
      DOCKER_SWARM_MANAGER_HOST:
        required: true
      DOCKER_SWARM_MANAGER_USER:
        required: true

permissions:
  deployments: write
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.stage }}
      url: ${{ inputs.deployUrl }}

    steps:
      # -> https://maxschmitt.me/posts/github-actions-ssh-key
      # this is not done, with an action, because this is a security risk
      - name: Set up SSH key for Docker Swarm Manager host
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOCKER_SWARM_MANAGER_SSH_KEY }}" > ~/.ssh/docker_host_key
          chmod 600 ~/.ssh/docker_host_key
          ssh-keyscan -H "${{ secrets.DOCKER_SWARM_MANAGER_HOST }}" >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/docker_host_key

      - name: Set DOCKER_HOST env
        run: echo "DOCKER_HOST=ssh://${{ secrets.DOCKER_SWARM_MANAGER_USER }}@${{ secrets.DOCKER_SWARM_MANAGER_HOST }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry on remote host
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker stack deploy on remote host
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          set -e
          VERSION=${{ inputs.version }} docker compose pull service
          VERSION=${{ inputs.version }} docker stack deploy -c docker-compose.yml --detach=false --with-registry-auth --prune ${{ inputs.stack }}
