name: Deploy Production

on:
  push:
    branches:
      - master
    tags:
      - '*'

permissions:
  deployments: write
  contents: read
  packages: write

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: get-tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  

  call-build-images:
    needs: get-latest-tag
    uses: ./.github/workflows/build-images.yml
    with:
      version: ${{ needs.get-latest-tag.outputs.tag }}

  call-deploy-stack:
    needs: call-build-images
    uses: ./.github/workflows/deploy-stack.yml
    with:
      version: ${{ needs.get-latest-tag.outputs.tag }}
      stage: Production
      deployUrl: https://dockerswarmstill.rocks
      stack: website-production
    secrets:
      DOCKER_SWARM_MANAGER_SSH_KEY: ${{ secrets.DOCKER_SWARM_MANAGER_SSH_KEY }}
      DOCKER_SWARM_MANAGER_HOST: ${{ secrets.DOCKER_SWARM_MANAGER_HOST }}
